title: Salman Chishti
author: Salman Chishti
email: 13schishti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is just a custom site Salman Chishti has set up on GitHub pages

# social links
twitter_username: salmanmkc # DO NOT include the @ character, or else the build will fail!
github_username:  salmanmkc # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
